Repository team-xquare/xquare-design-system-iOS, pull requests merged in 2023-08, with the labels that each got.

#30 🔀 :: (#15) XBlur 추가
  xquare-design-system-iOS/Sources/Blur/XBlur.swift
  xquare-design-system-iOS/Sources/Blur/XBlurStyle.swift
Labels: 기능 추가

#28 🔀 :: (#27) Font Register
  Package.swift
  xquare-design-system-iOS/Sources/Playground/DesignSystemPlaygroundView.swift
  xquare-design-system-iOS/Sources/Playground/Views/FontPlaygroundView.swift
  xquare-design-system-iOS/Sources/Typography/NotoSansKR.swift
  xquare-design-system-iOS/Sources/Typography/XFontStyle.swift
Labels: 기능 추가

#29 🔀 :: (#26) Alert 추가
  xquare-design-system-iOS/Sources/Alert/AlertPresenter.swift
  xquare-design-system-iOS/Sources/Alert/XAlert.swift
  xquare-design-system-iOS/Sources/Alert/XAlertButtonModel.swift
  xquare-design-system-iOS/Sources/Playground/DesignSystemPlaygroundView.swift
  xquare-design-system-iOS/Sources/Playground/Views/AlertPlaygroundView.swift
Labels: 기능 추가

#35 🔀 :: (#34) bottom sheet 구현
  xquare-design-system-iOS/Sources/Alert/XAlert.swift
  xquare-design-system-iOS/Sources/BottomSheet/XBottomSheet.swift
  xquare-design-system-iOS/Sources/BottomSheet/XBottomSheetStyle.swift
  xquare-design-system-iOS/Sources/Playground/DesignSystemPlaygroundView.swift
  xquare-design-system-iOS/Sources/Playground/Views/BottomSheetPlaygrondView.swift
Labels: 기능 추가

#38 🔀 :: (#37) bottom sheet 리팩토링
  xquare-design-system-iOS/Sources/BottomSheet/XBottomSheet.swift
  xquare-design-system-iOS/Sources/BottomSheet/XBottomSheetStyle.swift
Labels: 기능 추가, 리팩토링

#39 🔀 :: (#36) XDivider
  xquare-design-system-iOS/Sources/Divider/XDivider.swift
  xquare-design-system-iOS/Sources/Playground/DesignSystemPlaygroundView.swift
  xquare-design-system-iOS/Sources/Playground/Views/DividerPlaygroundView.swift
Labels: 기능 추가

#42 🔀 :: (#41) DropDown System
  xquare-design-system-iOS/Sources/DropDown/Cell/DropDownCell.swift
  xquare-design-system-iOS/Sources/DropDown/XDropDown.swift
  xquare-design-system-iOS/Sources/Playground/DesignSystemPlaygroundView.swift
  xquare-design-system-iOS/Sources/Playground/Views/DropDownPlaygroundView.swift
Labels: 기능 추가

#47 🔀 :: (#45) Textfield 디자인에 맞게 수정
  xquare-design-system-iOS/Sources/Textfield/XTextField.swift
Labels: 기능 추가

#49 🔀 :: (#48) DropDown 변경사항 변경
  xquare-design-system-iOS/Sources/DropDown/XDropDown.swift
Labels: 리팩토링
